# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2W\n\x0bNodeService\x12$\n\x0cSendDownload\x12\x08.Message\x1a\x08.Message\"\x00\x12\"\n\nSendUpload\x12\x08.Message\x1a\x08.Message\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=17
  _globals['_MESSAGE']._serialized_end=43
  _globals['_NODESERVICE']._serialized_start=45
  _globals['_NODESERVICE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
